### PR TITLE
Add useful testing information for stream encoding and packaging teams

### PR DESCRIPTION
**Pull request by defagos**
# Description

This PR documents tools available for inspecting and testing streams. This should help stream encoding and packaging teams be more autonomous in testing streams before they deliver them to our Pillarbox players.

# Changes made

- Enhance stream packaging documentation (extend it to encoding as well).

# Checklist

- [x] APIs have been properly documented (if relevant).
- [x] The documentation has been updated (if relevant).
- [x] New unit tests have been written (if relevant).
- [x] The demo has been updated (if relevant).

### CODE REVIEW

**Comment by defagos** [comment]
@amtins I added you as a reviewer since you might have some additional insights to provide. Documentation is in the DocC format but can still be conveniently [read online](https://github.com/SRGSSR/pillarbox-apple/blob/909-document-tools-available-for-encoding--packaging-teams-to-test-their-streams/Sources/Player/Player.docc/Articles/stream-encoding-and-packaging-advice.md), though some formatting will not be applied.

Thanks in advance for your help.

**Comment by amtins** [comment]
@defagos we can add: 
- [TSDuck](https://tsduck.io/) which is a toolkit,
- the [DASH](https://dashif-documents.azurewebsites.net/DASH-IF-IOP/master/DASH-IF-IOP.html) specification
- the [Supported Media for Google Cast](https://developers.google.com/cast/docs/media) which provides useful information for the encoding and packaging teams.

**Comment by defagos** [comment]
@amtins Thanks, I added TSDuck. The other tools are not really at home in the documentation of PillarboxPlayer since it only supports HLS.

The documentation is also targeting Apple platform needs specifically since PillarboxPlayer is a generic player for Apple platforms. I guess that once we have similar information for Android and the web we could gather all information as a shared consolidated page that is more specific to our company (and on which we could also mention internal tools like MMF).

**Comment by amtins** [comment]
@defagos my bad, I thought I was in pillarbox-documentation, misread 😅

**Review by amtins — APPROVED** [review]

**Pull request merged**
